const buszMenetrend = {
  jarat: "70",
  megallok: {
    stop1: "Szeged, Mars tér (Szent Rókus tér)",
    indulasiIdok: {},
    stop2: "Mars tér",
    indulasiIdok: {},
    stop3: "Bartók tér",
    indulasiIdok: {},
    stop4: "Széchenyi tér (Kelemen utca)",
    indulasiIdok: {},
    stop5: "Szeged, Torontál tér",
    indulasiIdok: {},
    stop6: "Újszeged, Gabonakutató",
    indulasiIdok: {},
    stop7: "Alsó kikötő sor",
    indulasiIdok: {},
    stop8: "Hatházak",
    indulasiIdok: {},
    stop9: "Szeged, Akácfa utca",
    indulasiIdok: {},
    stop10: "Füvészkert",
    indulasiIdok: {},
  },
};
